version: '3'

services:
  db:
    container_name: IN-relacional
    image: postgres:16.2
    environment:
      POSTGRES_DB: BI-local
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    volumes:
      - ./src/database/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - '5050:80'
    volumes:
      - ./src/database/pgadmin_data:/var/lib/pgadmin